//This was generated by AI using https://www.shadertoy.com/view/ltBGWh and https://arxiv.org/abs/2010.08735 as source material

uniform float iTime;
uniform float iTimeDelta;
uniform int iFrame;
uniform float iEventHorizon;
uniform vec3 iDiskColor;
uniform vec3 iCameraDirection;
uniform sampler2D iChannel0;
uniform vec3 iResolution;

in vec2 vTexCoord;
in vec4 vColor;
out vec4 fragColor;

const float PI = 3.14159265359;
const int MARCH_STEPS = 128;
const float DISTORTION_RADIUS_SCALE = 8.0;

struct Ray {
    vec3 origin;
    vec3 direction;
};

float hash(vec3 p) {
    p = fract(p * 0.3183099 + vec3(0.11, 0.17, 0.13));
    p *= 17.0;
    return fract(p.x * p.y * p.z * (p.x + p.y + p.z));
}

float noise(vec3 p) {
    vec3 cell = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(
            mix(mix(hash(cell), hash(cell + vec3(1.0, 0.0, 0.0)), f.x),
                    mix(hash(cell + vec3(0.0, 1.0, 0.0)), hash(cell + vec3(1.0, 1.0, 0.0)), f.x), f.y),
            mix(mix(hash(cell + vec3(0.0, 0.0, 1.0)), hash(cell + vec3(1.0, 0.0, 1.0)), f.x),
                    mix(hash(cell + vec3(0.0, 1.0, 1.0)), hash(cell + vec3(1.0, 1.0, 1.0)), f.x), f.y),
            f.z
    );
}

float fbm(vec3 p) {
    float value = 0.0;
    float amplitude = 0.5;
    for (int octave = 0; octave < 4; octave++) {
        value += amplitude * noise(p);
        p = p * 2.03 + vec3(7.1, 3.7, 5.9);
        amplitude *= 0.5;
    }
    return value;
}

mat2 rotation(float angle) {
    float sine = sin(angle);
    float cosine = cos(angle);
    return mat2(cosine, -sine, sine, cosine);
}

float arealRadius(float isotropicRadius, float schwarzschildRadius) {
    float scale = 1.0 + schwarzschildRadius / (4.0 * isotropicRadius);
    return isotropicRadius * scale * scale;
}

vec3 opticalCurvature(vec3 position, vec3 direction, float schwarzschildRadius) {
    float radius = max(length(position), schwarzschildRadius * 0.251);
    float a = schwarzschildRadius / (4.0 * radius);
    float derivative = -(a / radius) * (
    3.0 / (1.0 + a) + 1.0 / max(1.0 - a, 0.015)
    );
    vec3 gradient = normalize(position) * derivative;
    return gradient - direction * dot(gradient, direction);
}

float diskDensity(vec3 position, float schwarzschildRadius, out float physicalRadius) {
    float isotropicRadius = max(length(position.xz), 0.0001);
    physicalRadius = arealRadius(isotropicRadius, schwarzschildRadius);
    float innerRadius = 3.0 * schwarzschildRadius;
    float outerRadius = 10.0 * schwarzschildRadius;
    if (physicalRadius <= innerRadius || physicalRadius >= outerRadius
        || abs(position.y) > 0.32) {
        return 0.0;
    }
    float radialPosition = clamp(
            (physicalRadius - innerRadius) / (outerRadius - innerRadius),
            0.0,
            1.0
    );
    float radialMask = smoothstep(innerRadius, innerRadius * 1.12, physicalRadius)
    * (1.0 - smoothstep(outerRadius * 0.82, outerRadius, physicalRadius));
    float scaleHeight = mix(0.045, 0.105, radialPosition);
    float verticalMask = exp(-pow(position.y / scaleHeight, 2.0));

    float animationTime = iTime + clamp(iTimeDelta, 0.0, 0.05) * 0.5;
    float orbit = animationTime * mix(0.22, 0.07, sqrt(radialPosition));
    vec2 movingPosition = rotation(orbit) * position.xz;
    vec2 flowPosition = movingPosition / schwarzschildRadius;
    float broadClouds = fbm(vec3(flowPosition * 0.38, 1.7));
    float turbulentWisps = fbm(
            vec3(flowPosition * 0.92 + vec2(8.3, 3.1), 5.7)
    );
    float clumps = fbm(vec3(
            flowPosition * mix(1.35, 0.72, radialPosition) + vec2(2.4, 9.2),
            position.y / scaleHeight + 11.0
    ));
    float structure = smoothstep(
            0.22,
            0.88,
            broadClouds * 0.52 + turbulentWisps * 0.30 + clumps * 0.38
    );
    return radialMask * verticalMask * mix(0.025, 1.0, structure);
}

vec3 diskEmission(
        vec3 position,
        vec3 rayDirection,
        float physicalRadius,
        float schwarzschildRadius,
        float density
) {
    vec3 orbitalDirection = normalize(vec3(-position.z, 0.0, position.x));
    float orbitalSpeed = sqrt(
            schwarzschildRadius / max(2.0 * (physicalRadius - schwarzschildRadius), 0.0001)
    );
    orbitalSpeed = min(orbitalSpeed, 0.72);
    float lineOfSightSpeed = orbitalSpeed * dot(orbitalDirection, -rayDirection);
    float doppler = sqrt(max(1.0 - orbitalSpeed * orbitalSpeed, 0.01))
    / max(1.0 - lineOfSightSpeed, 0.12);
    float gravitationalRedshift = sqrt(max(1.0 - schwarzschildRadius / physicalRadius, 0.0));
    float frequencyShift = clamp(doppler * gravitationalRedshift, 0.35, 1.85);

    float normalizedRadius = physicalRadius / schwarzschildRadius;
    float temperatureProfile = pow(max(
            (1.0 - sqrt(3.0 / normalizedRadius))
            / (normalizedRadius * normalizedRadius * normalizedRadius),
            0.0
    ), 0.25);
    float heat = clamp(temperatureProfile / 0.214, 0.0, 1.0);
    vec3 color = mix(iDiskColor * 0.24, iDiskColor, smoothstep(0.0, 0.72, heat));
    color = mix(color, vec3(1.0, 0.88, 0.58), smoothstep(0.48, 0.88, heat * frequencyShift));
    color = mix(color, vec3(0.72, 0.84, 1.0), smoothstep(1.05, 1.55, heat * frequencyShift));
    return color * density * 3.2 * pow(frequencyShift, 3.0);
}

vec3 traceBlackHole(
        vec2 imagePosition,
        vec2 screenUv,
        out vec3 diskRadiance,
        out float backgroundTransmission
) {
    float schwarzschildRadius = iEventHorizon;
    float horizonRadius = schwarzschildRadius * 0.25;

    vec3 cameraPosition = normalize(iCameraDirection) * 4.0;
    vec3 forward = normalize(-cameraPosition);
    vec3 referenceUp = abs(forward.y) > 0.995
    ? vec3(0.0, 0.0, 1.0)
    : vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(forward, referenceUp));
    vec3 up = cross(right, forward);
    float fieldOfView = 0.72;

    Ray ray = Ray(
            cameraPosition,
            normalize(forward + fieldOfView * (imagePosition.x * right + imagePosition.y * up))
    );
    vec3 initialDirection = ray.direction;
    vec3 radiance = vec3(0.0);
    float transmittance = 1.0;
    float travelled = 0.0;
    bool captured = false;

    for (int stepIndex = 0; stepIndex < MARCH_STEPS; stepIndex++) {
        float radius = length(ray.origin);
        if (radius <= horizonRadius * 1.012) {
            captured = true;
            break;
        }
        if (travelled > 8.5 || (radius > 4.8 && dot(ray.origin, ray.direction) > 0.0)) {
            break;
        }

        float stepSize = clamp((radius - horizonRadius) * 0.12, 0.007, 0.070);
        if (abs(ray.origin.y) < 0.18 && length(ray.origin.xz) < 2.6) {
            stepSize = min(stepSize, 0.025);
        }
        vec3 midpointDirection = normalize(
                ray.direction + opticalCurvature(ray.origin, ray.direction, schwarzschildRadius) * (0.5 * stepSize)
        );
        vec3 midpoint = ray.origin + midpointDirection * (0.5 * stepSize);

        float physicalRadius;
        float density = diskDensity(midpoint, schwarzschildRadius, physicalRadius);
        if (density > 0.0001) {
            float opticalDepth = density * stepSize * 7.5;
            float absorbed = 1.0 - exp(-opticalDepth);
            radiance += transmittance * absorbed * diskEmission(
                    midpoint,
                    midpointDirection,
                    physicalRadius,
                    schwarzschildRadius,
                    density
            );
            transmittance *= exp(-opticalDepth * 0.72);
        }

        ray.direction = normalize(
                ray.direction + opticalCurvature(midpoint, midpointDirection, schwarzschildRadius) * stepSize
        );
        ray.origin += midpointDirection * stepSize;
        travelled += stepSize;
        if (transmittance < 0.001) break;
    }

    vec3 background = texture(iChannel0, screenUv).rgb;
    if (!captured) {
        float finalForward = dot(ray.direction, forward);
        if (finalForward <= 0.02) {
            captured = true;
        } else {
            float originalForward = max(dot(initialDirection, forward), 0.0001);
            vec2 originalProjection = vec2(
                    dot(initialDirection, right), dot(initialDirection, up)
            ) / (originalForward * fieldOfView);
            vec2 finalProjection = vec2(
                    dot(ray.direction, right), dot(ray.direction, up)
            ) / (finalForward * fieldOfView);

            vec2 projectionOffset = (
            finalProjection - originalProjection
            ) * DISTORTION_RADIUS_SCALE;
            float projectionOffsetLength = length(projectionOffset);
            projectionOffset *= 0.32 / (0.32 + projectionOffsetLength);

            mat2 imageJacobian = mat2(dFdx(imagePosition), dFdy(imagePosition));
            mat2 screenJacobian = mat2(dFdx(screenUv), dFdy(screenUv));
            vec2 screenOffset = screenJacobian * inverse(imageJacobian) * projectionOffset;
            vec2 lensedUv = screenUv + screenOffset;
            vec2 edgeDistance = min(lensedUv, vec2(1.0) - lensedUv);
            float validSample = smoothstep(0.0, 0.015, min(edgeDistance.x, edgeDistance.y));
            vec3 lensedBackground = texture(
                    iChannel0,
                    clamp(lensedUv, vec2(0.001), vec2(0.999))
            ).rgb;
            background = mix(background, lensedBackground, validSample);
        }
    }
    diskRadiance = radiance;
    backgroundTransmission = captured ? 0.0 : transmittance;
    return background;
}

void main() {
    vec2 imagePosition = vTexCoord * 2.0 - 1.0;
    float bounds = length(imagePosition);
    vec2 screenUv = gl_FragCoord.xy / iResolution.xy;
    vec3 originalScene = texture(iChannel0, screenUv).rgb;
    if (bounds >= 0.98) {
        discard;
    }

    float effectEnvelope = 1.0 - smoothstep(0.41, 0.49, bounds);
    vec2 sampleDirection = (iFrame % 2 == 0)
    ? vec2(0.24, -0.24)
    : vec2(0.24, 0.24);
    vec2 sampleOffset = fwidth(imagePosition) * sampleDirection;
    vec3 diskRadianceA;
    vec3 diskRadianceB;
    float transmissionA;
    float transmissionB;
    vec3 lensedSceneA = traceBlackHole(
            imagePosition - sampleOffset,
            screenUv,
            diskRadianceA,
            transmissionA
    );
    vec3 lensedSceneB = traceBlackHole(
            imagePosition + sampleOffset,
            screenUv,
            diskRadianceB,
            transmissionB
    );
    float distortionBlend = effectEnvelope;
    vec3 colorA = mix(originalScene, lensedSceneA, distortionBlend)
    * transmissionA + diskRadianceA;
    vec3 colorB = mix(originalScene, lensedSceneB, distortionBlend)
    * transmissionB + diskRadianceB;
    vec3 color = 0.5 * (colorA + colorB);

    float colorDelta = length(color - originalScene);
    if (colorDelta < 0.001) {
        discard;
    }
    fragColor = vec4(clamp(color, 0.0, 1.0) * vColor.rgb, vColor.a);
}