plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}


dependencies {
    implementation "net.bytebuddy:byte-buddy:1.18.11"

    jarJar "net.bytebuddy:byte-buddy:1.18.11"
    jarJar "de.javagl:obj:0.4.0"
    jarJar "de.javagl:jgltf-model:2.0.4"
    jarJar "de.javagl:jgltf-impl-v1:2.0.4"
    jarJar "de.javagl:jgltf-impl-v2:2.0.4"
    jarJar "com.twelvemonkeys.imageio:imageio-webp:3.13.1"
    jarJar "com.twelvemonkeys.imageio:imageio-core:3.13.1"
    jarJar "com.twelvemonkeys.imageio:imageio-metadata:3.13.1"
    jarJar "com.twelvemonkeys.common:common-lang:3.13.1"
    jarJar "com.twelvemonkeys.common:common-io:3.13.1"
    jarJar "com.twelvemonkeys.common:common-image:3.13.1"

    clientAdditionalRuntimeClasspath "net.bytebuddy:byte-buddy:1.18.11"
    clientAdditionalRuntimeClasspath "de.javagl:obj:0.4.0"
    clientAdditionalRuntimeClasspath "de.javagl:jgltf-model:2.0.4"
    clientAdditionalRuntimeClasspath "de.javagl:jgltf-impl-v1:2.0.4"
    clientAdditionalRuntimeClasspath "de.javagl:jgltf-impl-v2:2.0.4"
    clientAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-webp:3.13.1"
    clientAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-core:3.13.1"
    clientAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-metadata:3.13.1"
    clientAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-lang:3.13.1"
    clientAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-io:3.13.1"
    clientAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-image:3.13.1"

    dataAdditionalRuntimeClasspath "net.bytebuddy:byte-buddy:1.18.11"
    dataAdditionalRuntimeClasspath "de.javagl:obj:0.4.0"
    dataAdditionalRuntimeClasspath "de.javagl:jgltf-model:2.0.4"
    dataAdditionalRuntimeClasspath "de.javagl:jgltf-impl-v1:2.0.4"
    dataAdditionalRuntimeClasspath "de.javagl:jgltf-impl-v2:2.0.4"
    dataAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-webp:3.13.1"
    dataAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-core:3.13.1"
    dataAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-metadata:3.13.1"
    dataAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-lang:3.13.1"
    dataAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-io:3.13.1"
    dataAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-image:3.13.1"

    serverAdditionalRuntimeClasspath "net.bytebuddy:byte-buddy:1.18.11"
    serverAdditionalRuntimeClasspath "de.javagl:obj:0.4.0"
    serverAdditionalRuntimeClasspath "de.javagl:jgltf-model:2.0.4"
    serverAdditionalRuntimeClasspath "de.javagl:jgltf-impl-v1:2.0.4"
    serverAdditionalRuntimeClasspath "de.javagl:jgltf-impl-v2:2.0.4"
    serverAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-webp:3.13.1"
    serverAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-core:3.13.1"
    serverAdditionalRuntimeClasspath "com.twelvemonkeys.imageio:imageio-metadata:3.13.1"
    serverAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-lang:3.13.1"
    serverAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-io:3.13.1"
    serverAdditionalRuntimeClasspath "com.twelvemonkeys.common:common-image:3.13.1"

    runtimeOnly(project(':test'))
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

